# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-05 13:39:53


def data_visualization(data_raw):
    import json

    import plotly.graph_objects as go
    import plotly.io as pio

    # Create a boxplot to compare the distribution of Monthly Charges based on Churn status
    fig = go.Figure()

    fig.add_trace(
        go.Box(
            y=data_raw[data_raw["Churn"] == "Yes"]["MonthlyCharges"],
            name="Churn: Yes",
            boxmean="sd",  # Show the mean and standard deviation
        )
    )

    fig.add_trace(
        go.Box(
            y=data_raw[data_raw["Churn"] == "No"]["MonthlyCharges"],
            name="Churn: No",
            boxmean="sd",  # Show the mean and standard deviation
        )
    )

    # Update layout
    fig.update_layout(
        title="Distribution of Monthly Charges by Churn Status",
        xaxis_title="Churn",
        yaxis_title="Monthly Charges",
        boxmode="group",  # Group boxes of different categories together
    )

    # Convert figure to json and then to dictionary
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json if fig_json is not None else "{}")

    return fig_dict  # noqa: RET504
